import Header from "@/ui_components/Header";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import Footer from "@/ui_components/Footer";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "🍔Blog Next Django",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} transition-all duration-500 w-full bg-[#ffffff]`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
